---

### Rkhunter
- name: rkhunter settings
  template:
    src: rkhunter.conf.j2
    dest: /etc/rkhunter.conf
# Disabled since Rkhunter adds a job in cron.daily, so it isn't needed.
#  notify: rkhunter cron
#
#- name: rkhunter cron
#  cron:
#    name: "Rkhunter update"
#    minute: "0"
#    hour: "4"
#    day: "*"
#    job: "/usr/bin/rkhunter --cronjob --update --quiet; /usr/bin/rkhunter --cronjob -c --enable all --quiet"
  notify: rkhunter warning mails

- name: rkhunter warning mails
  lineinfile:
    dest: /etc/default/rkhunter
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^CRON_DAILY_RUN', line: 'CRON_DAILY_RUN="true"' }
    - { regexp: '^CRON_DB_UPDATE', line: 'CRON_DB_UPDATE="true"' }
    - { regexp: '^APT_AUTOGEN', line: 'APT_AUTOGEN="true"' }
  notify: rkhunter propup

- name: rkhunter propup
  command: 'rkhunter --propupd'
  notify: etckeeper update

### Iptables
- name: iptables restart
  command: 'iptables-restore -!< /etc/network/iptables'
  notify: iptables startup

- name: iptables startup
  lineinfile:
    dest: /etc/network/interfaces
    insertafter: "^iface eth0 inet static$"
    line: "    post-up iptables-restore < /etc/network/iptables"
  notify: etckeeper update


### Fail2ban
- name: fail2ban settings
  template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.conf
  notify: fail2ban restart

- name: fail2ban restart
  service:
    name: fail2ban
    state: restarted
  notify: etckeeper update
