---
- name: update rkhunter
  command: rkhunter --propupd

- name: iptables restore
# command: iptables-restore -! < /etc/network/iptables
  shell: iptables-restore < /etc/network/iptables

#- name: restart iptables
#  service: name=iptables state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted
