---

- name: apache2 restart
  service:
    name: apache
    state: restarted

- name: untar apache certificate
  command: 'tar xf /etc/ssl/"{{ scope }}externalCertificate.tar"'
  notify: wipe tarred SSL certificate

- name: wipe tarred SSL certificate
  command: 'shred -u /etc/ssl/"{{ scope }}externalCertificate.tar"'
