---

# Looks for changed files in order to put them into the commit message.
- name: etckeeper update
  shell: 'cd /etc && git ls-files -m'
  register: etckeeperCommit
  notify: etckeeper commit

- name: etckeeper commit
  command: 'etckeeper commit "{{ etckeeperCommit.stdout }}"'
  when: etckeeperCommit.stdout
