---
- name: Install MySQL server
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - automysqlbackup
  tags: mysql

- name: Prepare secure settings
  template: src=mysql_secure_installation.sql.j2 dest=/tmp/mysql_secure_installation.sql
  tags: mysql

- name: Secure MySQL installation
  command: "cat /tmp/mysql_secure_installation.sql | mysql"
  notify: restart mysql
  tags: mysql

- name: Prepare AutoMySQLBackup
  command: "mkdir -p /var/lib/automysqlbackup"
  tags: mysql

- name: Configure AutoMySQLBackup
  template: src=automysqlbackup.j2 dest=/etc/default/automysqlbackup
  tags: mysql
