---

### Etckeeper
# In Ubuntu, etckeeper is shipped with bzr as default CVS. Since I
# prefer using it together with Git, I install git first as dependency,
# so bzr won't be installed.
- name: Install Etckeeper.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - etckeeper
  tags: etckeeper

- name: Configure etckeeper for working with Git instead of Bzr.
  lineinfile:
    dest: /etc/etckeeper/etckeeper.conf
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^VCS="bzr"', line: '#VCS="bzr"' }
    - { regexp: '^#?VCS="git"', line: 'VCS="git"' }
    - { regexp: '^#AVOID_DAILY_AUTOCOMMITS=1', line: 'AVOID_DAILY_AUTOCOMMITS=1' }
  tags: etckeeper


- name: etckeeper init
  command: 'etckeeper init'
  tags: etckeeper

# Check if etckeeper was initialised before by looking for a previous commit message.
- name: etckeeper check init commit
  stat:
    path: /etc/.git/COMMIT_EDITMSG
  register: etckeeperYetCommited
  tags: etckeeper

- name: etckeeper first commit
  command: 'etckeeper commit "Initial commit."'
  when: not etckeeperYetCommited.stat.exists
  tags: etckeeper
