---

### Unattended-upgrades.

- name: unattended-upgrades settings
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 20unattended-upgrades, dest: /etc/apt/apt.conf.d/20auto-upgrades }
    - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/50unattended-upgrades}
  notify: apt-listchanges settings

### Apt-listchanges.
- name: apt-listchanges settings
  lineinfile:
    dest: /etc/apt/listchanges.conf
    state: present
    regexp: '^email_address=root'
    line: '^email_address="{{ smtpRecipient }}"'
  notify: debsums settings

### Debsums.
- name: debsums settings
  lineinfile:
    dest: /etc/default/debsums
    state: present
    regexp: '^CRON_CHECK=never'
    line: '^CRON_CHECK=weekly'
  notify: etckeeper update
