---

- name: logwatch settings
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
  notify: logwatch dir

- name: logwatch dir
  file:
    dest: /var/cache/logwatch
    state: directory
  notify: etckeeper update
