---

### NTP.

- name: ntp timezone
  command: 'ln -sf /usr/share/zoneinfo/"{{ ntpTimezone }}" /etc/localtime'
  notify: ntp cron

- name: ntp cron
  cron:
    name: "Time will be synced once at day."
    minute: "0"
    hour: "5"
    day: "*"
    job: "/usr/sbin/ntpdate {{ ntpServer }} > /dev/null 2>&1"

### Unattended-upgrades.

- name: unattended-upgrades settings
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 20unattended-upgrades, dest: /etc/apt/apt.conf.d/20auto-upgrades }
    - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/50unattended-upgrades}
  notify: etckeeper update

### sSMTP

- name: ssmtp hostname
  command: hostname -f
  register: hostname
  notify: ssmtp settings

- name: ssmtp settings
  template:
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
  notify: ssmtp revaliases

- name: ssmtp revaliases
  lineinfile:
    dest: /etc/ssmtp/revaliases
    line: "root:{{ smtpRecipient }}:{{ smtpServer }}"
  notify: etckeeper update

### Logwatch
- name: logwatch settings
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
  notify: logwatch dir

- name: logwatch dir
  file:
    dest: /var/cache/logwatch
    state: directory
  notify: etckeeper update

### SNMP
- name: snmp settings
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
  notify: snmp restart

- name: snmp restart
  service:
    name: snmpd
    state: restarted
  notify: etckeeper update

### Webmin
- name: webmin apt key
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present
  notify: webmin install

- name: webmin install
  apt:
    update_cache: yes
    name: webmin
  notify: webmin certificate

- name: webmin certificate
  copy:
    src: miniserv.pem
    dest: /etc/webmin/miniserv.pem
  notify: webmin restart

- name: webmin restart
  service:
    name: webmin
    state: restarted
  notify: etckeeper update

### NRPE
- name: nrpe settings
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  notify: nrpe restart

- name: nrpe restart
  service:
    name: nagios-nrpe-server
    state: restarted
  notify: etckeeper update
