---

- name: ntp timezone
  command: 'ln -sf /usr/share/zoneinfo/"{{ ntpTimezone }}" /etc/localtime'
  notify: ntp settings

- name: ntp settings
  lineinfile:
    dest: /etc/ntp.conf
    state: present
    insertafter: "{{ item.after }}"
    line: "{{ item.line }}"
  with_items:
    - { after: 'EOF', line: 'interface ignore wildcard' }
    - { after: 'EOF', line: 'interface listen 127.0.0.1' }
  notify: ntp restart

- name: ntp restart
  service:
    name: ntp
    state: restarted
  notify: etckeeper update
