---

- name: ssmtp hostname
  command: hostname -f
  register: hostname
  notify: ssmtp settings

- name: ssmtp settings
  template:
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
  notify: ssmtp revaliases

- name: ssmtp revaliases
  lineinfile:
    dest: /etc/ssmtp/revaliases
    line: "root:{{ smtpRecipient }}:{{ smtpServer }}"
  notify: etckeeper update
