---
- name: Start Iptables at boot time.
  apt:
    name: iptables-persistent
    state: present

- name: Configure Iptables.
  template:
    src: iptables.rules.v4.j2
    dest: /etc/iptables/rules.v4
# Another way to create protocol+port-based rules
#   lineinfile:
#     dest: /etc/iptables/rules.v4
#     regexp: "^-A INPUT -s {{ publicIP }} -p {{ item.proto }} -m {{ item.proto }} --dport {{ item.port }} -j ACCEPT$"
#     line: "-A INPUT -s {{ publicIp }} -p {{ item.proto }} -m {{ item.proto }} --dport {{ item.port }} -j ACCEPT"
#     insertafter: "^:OUTPUT ACCEPT \[\d*:\d*\]$"
# with_items:
#   - { proto: tcp, port: 22 }
#   - { proto: tcp, port: 80 }
  notify: iptables restart
  tags: iptables
