---

### Rkhunter
- name: Install Rkhunter.
  apt:
    name: rkhunter
    state: present
  notify: rkhunter settings
  tags: rkhunter

### Iptables
- name: Configure Iptables.
  template:
    src: iptables.rules.j2
    dest: /etc/network/iptables
# Another way to create protocol+port-based rules
#   lineinfile:
#     dest: /etc/network/iptables
#     regexp: "^-A INPUT -s {{ publicIP }} -p {{ item.proto }} -m {{ item.proto }} --dport {{ item.port }} -j ACCEPT$"
#     line: "-A INPUT -s {{ publicIp }} -p {{ item.proto }} -m {{ item.proto }} --dport {{ item.port }} -j ACCEPT"
#     insertafter: "^:OUTPUT ACCEPT \[\d*:\d*\]$"
# with_items:
#   - { proto: tcp, port: 22 }
#   - { proto: tcp, port: 80 }
  notify: iptables restart
  tags: iptables

### Fail2ban
- name: Install Fail2ban.
  apt:
    name: fail2ban
    state: present
  notify: fail2ban settings
  tags: fail2ban

