---

- name: Install Tomcat 7 software
  apt: name={{ item }} state=present
  with_items:
    - tomcat7
    - libtomcat7-java
    - tomcat7-admin
    - tomcat7-common
  register: tomcatInstallation
  tags:
    - tomcat

- name: Configure Tomcat Admin GUI
  template: src=tomcat-users.xml.j2 dest=/var/lib/tomcat7/conf/tomcat-users.xml
  notify: restart tomcat
  tags:
  - tomcat

- name: Put Java KeyStore certificate
  when: tomcatInstallation|success
  copy: src=jssecacerts dest=/usr/lib/jvm/default-java/jre/lib/security owner=root group=root mode=0640
  tags:
  - tomcat

