---

# Logwatch needs 'mail' tool in order to send daily reports.
- name: Install Logwatch.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mailutils
    - logwatch
  notify: logwatch settings
  tags: logwatch
