---

# Logwatch needs 'mail' tool in order to send daily reports.
- name: Install Logwatch.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mailutils
    - logwatch
  tags: logwatch

- name: Configure main Logwatch configuration file.
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
  tags: logwatch

- name: Create tmp dir (not created by default).
  file:
    dest: /var/cache/logwatch
    state: directory
  tags: logwatch

### etckeeper commit
- name: Commit etckeeper
  debug:
    msg: "Commit Logwatch changes to etckeeper."
  notify: etckeeper update
  tags: logwatch
