---
- include: apt.yml
- include: purge-old-kernels.yml
- include: ntp.yml
- include: ssmtp
- include: logwatch
- include: monitoring.yml

### Apparmor is removed for testing purposes.
- name: Remove apparmor
  apt:
    name: apparmor
    state: absent
  notify: etckeeper update
  tags: apparmor

### UFW will removed since I use Iptables.
- name: UFW uninstall
  apt:
    name: ufw
    state: absent
  notify: etckeeper update
  tags:
    - ufw
    - iptables

- include: webmin.yml
