---

- include: apt.yml
- include: ntp.yml
- include: ssmtp.yml
- include: logwatch.yml
- include: monitoring.yml
- include: webmin.yml

### Purging old kernels, but keeps the running one and two latest also.
# This script is a part of «bikeshed» Ubuntu package, which is,
# according to its description, a "random useful tools that do not yet
# have a permanent home".
# Since we only need this script and not the whole package,
# previously was extracted and put apart, preserving both path and
# permissions.
- name: Purge old kernels
  copy:
    src: purge-old-kernels
    dest: /usr/bin/purge-old-kernels
    mode: 0755
  tags: purge-old-kernels

### Purge-old-kernels
- name: purge-old-kernels run
  command: /usr/bin/purge-old-kernels -qy
  tags: purge-old-kernels

- name: Run purge-old-kernels monthly
  cron:
    name: "Remove old kernels monthly"
    minute: "30"
    hour: "3"
    day: "1"
    job: "/usr/bin/purge-old-kernels -qy > /dev/null 2>&1"
  tags: purge-old-kernels

### Apparmor is removed for testing purposes.
- name: Remove apparmor
  apt:
    name: apparmor
    state: absent
  tags: apparmor

### UFW will removed since I use Iptables.
- name: UFW uninstall
  apt:
    name: ufw
    state: absent
  tags:
    - ufw
    - iptables

- name: Configure Vim as default editor
  command: 'update-alternatives --set editor /usr/bin/vim.basic'
  tags: vim

- name: Reduce the server's configuration to bufferbloat
  sysctl:
    name: net.core.default_qdisc
    value: fq_codel
    state: present
    reload: yes
  tags: bufferbloat

- name: Add some extra entropy
  apt:
    name: rng-tools
    state: present
  tags: rng

# Add RNG module to /etc/modules to load it at boot time.
- name: rng boot time
  lineinfile:
    dest: /etc/modules
    state: present
    insertafter: EOF
    line: "tpm_rng"
  tags: rng

### etckeeper commit
- name: Commit etckeeper
  debug:
    msg: "Commit changes to etckeeper."
  notify: etckeeper update
  tags:
    - purge-old-kernels
    - apparmor
    - ufw
    - iptables
    - vim
    - bufferbloat
    - rng
