---

###
# If we have to set up network settings (eg. routes), change root
# password, create new users, etc. , here is a good place to do so.
###

### APT
- name: Update repos and keep installed packages up to date.
  apt:
    update_cache: yes
    upgrade: safe
  tags: update

### NTP
- name: Ensure that box time is right and keep synced all day long.
  command: 'ntpdate "{{ ntpServer }}"'
  notify: ntp timezone
  tags: ntp

### Unattended-upgrades
- name: Install Unattended-upgrades.
  apt:
    name: unattended-upgrades
    state: present
  notify: unattended-upgrades settings
  tags: unattended-upgrades

### sSMTP
- name: Install sSMTP.
  apt:
    name: ssmtp
    state: present
  notify: ssmtp hostname
  tags: ssmtp

### Logwatch
# Logwatch needs 'mail' tool in order to send daily reports.
- name: Install Logwatch.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mailutils
    - logwatch
  notify: logwatch settings
  tags: logwatch

### SNMP
- name: Install SNMP.
  apt:
    name: snmpd
    state: present
  notify: snmp settings
  tags: snmp

### Apparmor is removed for testing purposes.
#- name: Disable Apparmor
# Commented since doesn't work.
#  service:
#    name: apparmor
#    enabled: no
#    state: stopped

# Another way to do the same, not Ansible style:
#  command: 'update-rc.d -f apparmor remove'
- name: Remove apparmor
  apt:
    name: apparmor
    state: absent
  notify: etckeeper update
  tags: apparmor

### UFW will removed since I use Iptables.
- name: UFW uninstall
  apt:
    name: ufw
    state: absent
  notify: etckeeper update
  tags:
    - ufw
    - iptables
