---
### SNMP
- name: Install SNMP.
  apt:
    name: snmpd
    state: present
  tags: snmp

- name: Copy snmpd.conf configuration file.
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
  notify: snmp restart
  tags: snmp

### NRPE
- name: NRPE Nagios server
  apt:
    name: nagios-nrpe-server
    state: present
  tags:
    - nagios
    - nrpe

- name: Copy main NRPE configuration file.
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  notify: nrpe restart

### Etckeeper commit
- name: Commit etckeeper
  debug:
    msg: "Commit monitoring related changes to etckeeper."
  notify: etckeeper update
  tags: 
    - snmp
    - nagios
    - nrpe
